threads: 64

### Muscle Alignment: sfile_muscle
#### < 1000 sequences
align: []

#### > 1000 sequences
super5: []

### IQ Tree (Combination of Align and Super5): sfile_iqtree
genes: []

### Gene - Gene Associations: sfile_geneGene, sfile_alisim
gene1: ['P03066']

gene2: ['P0AFY6']