threads: 64

### Muscle Alignment: sfile_muscle
#### < 1000 sequences
align: []

#### > 1000 sequences
super5: []

### IQ Tree (Combination of Align and Super5): sfile_iqtree
genes: []

### Gene - Gene Associations: sfile_geneGene, sfile_alisim
#### backbone genes
gene1: ['P0AFY6']

#### cargo genes
gene2: ['P0AFY6','P03066']

### alisim configs
num_bootstraps: 1000
min_shared_leaves: 20
random_seed: 1